# Generated by Django 2.1.3 on 2018-11-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='pokemon/photos', verbose_name='фотография'),
        ),
    ]
