# Generated by Django 2.1.3 on 2018-11-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181114_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
